services:
  updater:
    build: .
    container_name: docker-auto-updater

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
      - ./config:/app/config

    restart: always
